name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace placeholder with real widget URL
        run: |
          sed "s|{{WIDGET_URL1}}|$WIDGET_URL1|g" index.html > final.html
          mv final.html index.html
        env:
          WIDGET_URL1: ${{ vars.WIDGET_URL1 }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
