name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace placeholder with actual widget URL
        run: |
          sed "s|{{WIDGET_URL1}}|$WIDGET_URL1|g" index.html > final_index.html
          mv final_index.html index.html
        env:
          WIDGET_URL1: ${{ secrets.WIDGET_URL1 }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
