name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Replace widget placeholder
        run: |
          echo "Zamieniam {{WIDGET_URL1}} na: $WIDGET_URL1"
          sed "s|{{WIDGET_URL1}}|$WIDGET_URL1|g" index.html > index_final.html
          mv index_final.html index.html
        env:
          WIDGET_URL1: ${{ vars.WIDGET_URL1 }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
