name: GitHub Pages Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Replace env variable in HTML
        run: |
          mkdir site
          envsubst < index.html > site/index.html
        env:
          WIDGET_URL1: ${{ secrets.WIDGET_URL1 }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
