name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pages
        uses: actions/configure-pages@v5

      # - name: Prepare site directory and replace variable
      #   run: |
      #     mkdir -p site
      #     cp index.html site/
      #     sed -i "s|{{WIDGET_URL1}}|${{ secrets.WIDGET_URL1 }}|g" site/index.html

      - name: Prepare site directory and replace variable
        shell: bash
        run: |
          mkdir -p site
          cp index.html site/index.html
          chmod u+w site/index.html
          sed -i "s|{{WIDGET_SCRIPT}}|$(printf '%s' '${{ secrets.WIDGET_SCRIPT }}' | sed 's/[&]/\\&/g')|g" site/index.html
        env:
          WIDGET_URL1: ${{ secrets.WIDGET_URL1 }}



      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
